name: ft-test

on: pull_request

jobs:
  coding-style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check the coding style
      run: |
          cargo fmt -- --check

  build:
    runs-on: ubuntu-latest
    needs: coding-style

    steps:
    - uses: actions/checkout@v2
    - name: Build ft
      run: |
          cargo build

  tests:
    runs-on: ubuntu-latest
    needs: coding-style

    steps:
    - uses: actions/checkout@v2
    - name: Run Unit Tests and Documentation examples
      run: |
          cargo test
    - name: Run Functional Tests
      run: |
          cargo run -- -f tests/ft_for_ft.yml
